### ISSUE TITLE
[Bug]: Compressed SLCs are getting created incorrectly for the single update workflow

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/dolphin#50]
Here's a sample correlation matrix using 1 Fringe-created CompSlc and 5 normal SLCs:
![2023-02-17-1676665212891](https://user-images.githubusercontent.com/8291800/219786307-14918d44-d1ab-4289-9519-de4fbcdedb57.jpeg)

Here's the same correlation matrix, testing with dolphin functions (top row)
![2023-02-17-1676664648266](https://user-images.githubusercontent.com/8291800/219786312-eb76011a-28be-4d85-900d-1b5c9c4d97f8.jpeg)
(edit: this was not the result of a workflow, but was from testing each step without referencing to the first date)

The fact that it's lower correlation than all others is a clear bug, though it was basically getting ignored in the full sequential workflow (why it's been undetected until now).

**Comment by scottstanie** [comment]
To the problem note here: doing the SLC compression without referencing the phase value at each date to something (i.e. day 0) will lead to a garbage compressed SLC. 

That's what Miaplpy does that here https://github.com/insarlab/MiaplPy/blob/1dd79ca805c802158f4c22222bdc6047bd84e174/miaplpy/lib/utils.pyx#L241-L244 where it's always referenced to the first image (which may be a compressed SLC). Fringe does the referenced to the first non-compressed SLC.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/8291800/220718352-61dd2128-1b34-4b5b-ba70-00bb930b999f.png">

**Comment by hfattahi** [comment]
Too late to ask. Which way did you choose? In my opinion what we did in Fringe is the right approach.

**Comment by scottstanie** [comment]
Oh definitely not too late @hfattahi haha. I just wanted to merge this to move forward on the repeated-single-update test.

- For the single update version that's trying to do @mirzaees 's algorithm, I have the phase linking outputs referenced to the first SLC (which could be compressed) 
- For the sequential workflow, I tried to keep it like fringe, where each new ministack increments the reference index by one (so it's referenced to the first non-compressed SLC, then there's the datum adjustment at the end).

but i'll be testing both soon to see if either of those seems wrong.

**Comment by hfattahi** [comment]
Sounds good. Thanks for the info.
